import React, { useState, useEffect } from 'react';
import { supabase } from './supabase';
import { useCurrency } from './CurrencyContext';

const platformIcons = {
  instagram: '📸', tiktok: '🎵', youtube: '▶️', twitter: '🐦',
    facebook: '👤', telegram: '✈️', snapchat: '👻', linkedin: '💼',
      spotify: '🎵', discord: '🎮', twitch: '🎮', custom: '⚙️'
      };
      const platformColors = {
        instagram: '#E1306C', tiktok: '#00d4ff', youtube: '#FF0000',
          twitter: '#1DA1F2', facebook: '#1877F2', telegram: '#0088cc',
            snapchat: '#FFFC00', linkedin: '#0077B5', custom: '#7b2fff'
            };

            export default function Marketplace({ user, onNav }) {
              const { format } = useCurrency();
                const [services, setServices] = useState([]);
                  const [loading, setLoading] = useState(true);
                    const [search, setSearch] = useState('');
                      const [platform, setPlatform] = useState('');
                        const [showAll, setShowAll] = useState(false);
                          const [selected, setSelected] = useState(null);
                            const [link, setLink] = useState('');
                              const [qty, setQty] = useState('');
                                const [ordering, setOrdering] = useState(false);
                                  const [ordered, setOrdered] = useState(false);
                                    const [orderError, setOrderError] = useState('');

                                      useEffect(() => { loadServices(); }, []);

                                        const loadServices = async () => {
                                            setLoading(true);
                                                const { data } = await supabase
                                                      .from('services').select('*')
                                                            .eq('is_active', true)
                                                                  .order('is_featured', { ascending: false })
                                                                        .order('created_at', { ascending: false });
                                                                            if (data) setServices(data);
                                                                                setLoading(false);
                                                                                  };

                                                                                    const featuredServices = services.filter(s => s.is_featured);
                                                                                      const otherServices = services.filter(s => !s.is_featured);
                                                                                        const availablePlatforms = [...new Set(otherServices.map(s => s.platform))].filter(Boolean);

                                                                                          const filteredOthers = otherServices.filter(s => {
                                                                                              const matchPl = !platform || s.platform === platform;
                                                                                                  const matchQ = !search || s.name.toLowerCase().includes(search.toLowerCase());
                                                                                                      return matchPl && matchQ;
                                                                                                        });

                                                                                                          const cost = selected && qty
                                                                                                              ? (parseFloat(qty) / 1000 * parseFloat(selected.price_per_1k)).toFixed(4)
                                                                                                                  : '0.00';

                                                                                                                    const placeOrder = async () => {
                                                                                                                        setOrderError('');
                                                                                                                            if (!link) { setOrderError('Enter your link'); return; }
                                                                                                                                const q = parseInt(qty);
                                                                                                                                    if (!q || q < selected.min_qty || q > selected.max_qty) {
                                                                                                                                          setOrderError(`Quantity must be ${selected.min_qty} – ${selected.max_qty}`);
                                                                                                                                                return;
                                                                                                                                                    }
                                                                                                                                                        const totalCost = parseFloat(cost);
                                                                                                                                                            if (totalCost > user.balance) { setOrderError('Insufficient balance'); return; }

                                                                                                                                                                setOrdering(true);
                                                                                                                                                                    const orderRef = 'NF-' + Date.now();

                                                                                                                                                                        const { error: orderErr } = await supabase.from('orders').insert({
                                                                                                                                                                              order_ref: orderRef,
                                                                                                                                                                                    user_id: user.id,
                                                                                                                                                                                          service_id: selected.id,
                                                                                                                                                                                                service_name: selected.name,
                                                                                                                                                                                                      platform: selected.platform,
                                                                                                                                                                                                            link, quantity: q, cost: totalCost,
                                                                                                                                                                                                                  status: 'pending', progress: 0,
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                          if (orderErr) { setOrderError('Order failed: ' + orderErr.message); setOrdering(false); return; }

                                                                                                                                                                                                                              await supabase.from('users').update({ balance: user.balance - totalCost }).eq('id', user.id);
                                                                                                                                                                                                                                  await supabase.from('transactions').insert({
                                                                                                                                                                                                                                        user_id: user.id, type: 'order', amount: -totalCost,
                                                                                                                                                                                                                                              description: `Order: ${selected.name}`, ref_id: orderRef,
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                      // ─── FULLY AUTOMATIC: Send to provider API if configured ───
                                                                                                                                                                                                                                                          if (selected.provider_api_url && selected.provider_api_key && selected.provider_service_id) {
                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                        const res = await fetch('https://nexusflow-proxy.meharsufyanghani10.workers.dev', {
                                                                                                                                                                                                                                                                                  method: 'POST',
                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                        'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                            body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                        url: selected.provider_api_url,
                                                                                                                                                                                                                                                                                                                                                    key: selected.provider_api_key,
                                                                                                                                                                                                                                                                                                                                                                action: 'add',
                                                                                                                                                                                                                                                                                                                                                                            service: selected.provider_service_id,
                                                                                                                                                                                                                                                                                                                                                                                        link, quantity: q,
                                                                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                  const providerData = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                          if (providerData && providerData.order) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase.from('orders').update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                vendor_order_id: String(providerData.order),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            status: 'in_progress',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }).eq('order_ref', orderRef);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else if (providerData && providerData.error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await supabase.from('orders').update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    provider_note: `Provider error: ${providerData.error}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }).eq('order_ref', orderRef);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase.from('orders').update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              provider_note: `Auto-placement failed: ${e.message}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }).eq('order_ref', orderRef);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setOrdering(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setOrdered(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => { setSelected(null); setOrdered(false); setLink(''); setQty(''); }, 2500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const ic = (p) => platformIcons[p] || '⚙️';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const cl = (p) => platformColors[p] || '#7b2fff';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ServiceCard = ({ s }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`mkt-card ${s.is_featured ? 'mkt-featured' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => { setSelected(s); setLink(''); setQty(s.min_qty); setOrderError(''); }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {s.is_featured && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            position: 'absolute', top: '-1px', right: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: 'linear-gradient(135deg,var(--gold2),var(--gold))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#000', fontSize: '8px', fontWeight: 800, padding: '3px 8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: '0 0 6px 6px', letterSpacing: '1px', fontFamily: 'var(--fd)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}>⭐ FEATURED</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontSize: '22px' }}>{ic(s.platform)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: '9px', padding: '2px 7px', borderRadius: '10px', fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: `${cl(s.platform)}18`, color: cl(s.platform),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: `1px solid ${cl(s.platform)}30`, textTransform: 'uppercase', letterSpacing: '1px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>{s.platform}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontWeight: 700, fontSize: '13px', marginBottom: '4px', color: 'var(--text)' }}>{s.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '11px', color: 'var(--text3)', marginBottom: '12px', flex: 1, lineHeight: 1.5 }}>{s.description}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontFamily: 'var(--fm)', fontSize: '15px', fontWeight: 700, color: 'var(--gold)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {format(parseFloat(s.price_per_1k))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: '9px', color: 'var(--text3)' }}>per 1,000</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ textAlign: 'right' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: '9px', color: 'var(--text3)' }}>Min: {(s.min_qty || 0).toLocaleString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '9px', color: 'var(--text3)' }}>Max: {(s.max_qty || 0).toLocaleString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="btn bp bsm bw" style={{ marginTop: '12px' }}>Order Now →</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* ─── FEATURED SERVICES ─── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!loading && featuredServices.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="st">⭐ Featured Services
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ fontSize: '9px', color: 'var(--text3)', fontWeight: 400, letterSpacing: '1px', marginLeft: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          — Handpicked by admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mkt-grid" style={{ marginBottom: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {featuredServices.map(s => <ServiceCard key={s.id} s={s} />)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* ─── ALL SERVICES ─── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="st" style={{ margin: 0 }}>🛒 All Services</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {otherServices.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{ fontSize: '9px', color: 'var(--text3)' }}>{otherServices.length} available</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="btn bgh bsm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ marginLeft: 'auto' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setShowAll(!showAll)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {showAll ? '▲ Collapse' : '▼ Browse All'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {showAll && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', gap: '8px', marginBottom: '14px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input className="srch-inp" style={{ flex: 1, minWidth: '140px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="🔍 Search services..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={search} onChange={e => setSearch(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <select className="sel" style={{ width: '150px', flexShrink: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={platform} onChange={e => setPlatform(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="">🌐 All Platforms</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {availablePlatforms.map(p => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option key={p} value={p}>{ic(p)} {p}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
